import argparse
import os
import sys

from . import devices as D
from . import planners as P


def fmt_bytes(n):
    for unit, div in (("GB", 1 << 30), ("MB", 1 << 20), ("KB", 1 << 10)):
        if n >= div:
            v = n / div
            return f"{v:.0f} {unit}" if v >= 10 else f"{v:.1f} {unit}"
    return f"{n} B"


def fmt_time(t):
    if t is None:
        return "n/a"
    return f"{t * 1e6:.1f} us" if t < 1e-3 else f"{t * 1e3:.2f} ms"


def show(dev):
    out = [f"{dev['name']}  [{' > '.join(dev['path'])}]", f"  id: {dev['id']}   archetype: {dev['archetype']} "
           f"({D.ARCHETYPES[dev['archetype']]})",
           f"  units: {dev['units']['count']} x {dev['units']['name']}   dtypes: {', '.join(dev['dtypes'])}"]
    if dev.get("vector"):
        out.append(f"  vector: {dev['vector']['bits']}-bit, {dev['vector']['regs']} registers")
    mu = dev.get("matrix_unit")
    if mu:
        out.append(f"  matrix unit: {mu['name']}  {mu['m']}x{mu['n']}x{mu['k']}  ({', '.join(mu['dtype'])})")
    out.append("  memory:")
    for m in dev["memory"]:
        out.append(f"    {m['name']:<44} {fmt_bytes(m['kb'] * 1024):>8}  {m['scope']}")
    d = dev["dram"]
    out.append(f"    {d['name']:<44} {str(d['gb']) + ' GB' if d['gb'] else '?':>8}  {d['gbps'] or '?'} GB/s")
    if dev["peak_gflops"]:
        out.append("  peak: " + ", ".join(f"{t} {g / 1000:g} T" for t, g in dev["peak_gflops"].items()))
    out.append("  programming: " + "; ".join(dev["programming"]))
    out.append("  gotchas:")
    out += [f"    - {g}" for g in dev["gotchas"]]
    out.append(f"  verified: {dev['verified']}" + ("" if dev["verified"] else "   check: " + ", ".join(dev.get("sources_to_check", []))))
    return "\n".join(out)


def plan_text(dev, p):
    out = [f"{dev['name']}  [{' > '.join(dev['path'])}]",
           f"GEMM {p['M']}x{p['N']}x{p['K']} {p['dtype']}   archetype: {p['archetype']}", ""]
    out.append(f"  {'level':<30}{'tile / shape':<44}{'uses':>10}{'capacity':>11}")
    for t in p["tiles_list"]:
        if t["use"] is None:
            use, cap = "", ""
        elif t.get("unit"):
            use, cap = f"{t['use']} {t['unit']}", str(t["cap"])
        else:
            use, cap = fmt_bytes(t["use"]), fmt_bytes(t["cap"]) if t["cap"] else ""
        out.append(f"  {t['level']:<30}{t['shape']:<44}{use:>10}{cap:>11}")
    out += ["", "Why:"] + [f"  - {n}" for n in p["notes"]]
    out += ["", "Roofline-style estimate (an upper bound, not a measurement; assumes the micro-kernel reaches peak):",
            f"  arithmetic intensity {p['ai']:.1f} FLOP/B" + (f" vs machine balance {p['balance']:.1f}" if p["balance"] else " (no peak data)"),
            f"  DRAM traffic {fmt_bytes(int(p['traffic']))}, compute {fmt_time(p['t_comp'])}, data movement {fmt_time(p['t_dma'])}"]
    if p["pct_peak"] is not None:
        out.append(f"  => {p['bound']}-bound, at most about {p['pct_peak']:.0f}% of peak, total {fmt_time(p['t'])}")
    return "\n".join(out)


def compare_rows(devs, dt, M, N, K, ids=None):
    rows, skipped = [], []
    for d in devs:
        if ids and d["id"] not in ids:
            continue
        try:
            p = P.plan(d, dt, M, N, K)
        except P.NoFit as e:
            skipped.append((d["id"], str(e)))
            continue
        waste = 100 * (1 - p["flops"] / p["flops_padded"])
        rows.append([d["id"], d["path"][1], p["outer"], p["inner"], p["resident"], f"{waste:.0f}%",
                     f"{p['ai']:.0f}", f"{p['balance']:.0f}" if p["balance"] else "?", p["bound"],
                     f"{p['pct_peak']:.0f}%" if p["pct_peak"] is not None else "?"])
    return rows, skipped


HEAD = ["device", "class", "outer tile", "inner unit", "tile lives in", "pad waste", "FLOP/B", "balance", "bound", "% peak"]


def table(rows, md=False):
    if md:
        lines = ["| " + " | ".join(HEAD) + " |", "|" + "|".join("---" for _ in HEAD) + "|"]
        lines += ["| " + " | ".join(r) + " |" for r in rows]
        return "\n".join(lines)
    w = [max(len(HEAD[i]), *(len(r[i]) for r in rows)) for i in range(len(HEAD))]
    fmt = "  ".join(f"{{:<{x}}}" for x in w)
    return "\n".join([fmt.format(*HEAD), fmt.format(*("-" * x for x in w))] + [fmt.format(*r) for r in rows])


def gen_docs(devs, outdir):
    os.makedirs(outdir, exist_ok=True)
    lines = ["# Device taxonomy and tiling comparison", "", "Generated by `python3 -m atlas docs`. Do not edit by hand.", "",
             "## Hierarchy", "", "```", D.render_tree(devs), "```", "",
             "Top level answers one question: **who moves data between memories?** That decides how you tile.", "",
             "| Class | Who moves data | You tile for |", "|---|---|---|",
             "| General-purpose processors | hardware caches (implicit) | cache capacity and associativity, register file |",
             "| Parallel accelerators | hardware schedules thread blocks; you stage tiles in shared memory | shared memory + registers per block, number of blocks vs units |",
             "| Software-managed accelerators | you (or the compiler) issue DMA into a scratchpad | exact scratchpad capacity, DMA alignment, unit shape |",
             "| Simulated | whatever the model says | the model |", ""]
    cases = [("Large square GEMM (training/prefill-like)", "f16", 4096, 4096, 4096),
             ("Skinny GEMM (batch-16 decode-like)", "f16", 16, 4096, 4096),
             ("Large square GEMM, f32", "f32", 1024, 1024, 1024),
             ("Large square GEMM, int8", "i8", 2048, 2048, 2048)]
    for title, dt, M, N, K in cases:
        rows, skipped = compare_rows(devs, dt, M, N, K)
        lines += [f"## {title}: M={M} N={N} K={K} {dt}", "", table(rows, md=True), ""]
        if skipped:
            lines += ["Not shown (no native path): " + ", ".join(f"`{i}`" for i, _ in skipped), ""]
    with open(os.path.join(outdir, "comparison.md"), "w") as f:
        f.write("\n".join(lines) + "\n")
    return os.path.join(outdir, "comparison.md")


def main(argv=None):
    ap = argparse.ArgumentParser(prog="atlas", description="Device taxonomy and teaching tiling planner")
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("tree", help="print the device hierarchy")
    s = sub.add_parser("show", help="print one device card"); s.add_argument("id")
    for name in ("tile", "compare"):
        s = sub.add_parser(name)
        if name == "tile":
            s.add_argument("id")
        else:
            s.add_argument("--ids", help="comma-separated device ids"); s.add_argument("--md", action="store_true")
        s.add_argument("--m", type=int, default=1024); s.add_argument("--n", type=int, default=1024)
        s.add_argument("--k", type=int, default=1024); s.add_argument("--dtype", default="f16", choices=sorted(P.DT))
    sub.add_parser("audit", help="list data-quality gaps")
    s = sub.add_parser("docs", help="regenerate docs/comparison.md"); s.add_argument("--out", default=os.path.join(D.HERE, "..", "docs"))
    a = ap.parse_args(argv)

    devs = D.load()
    try:
        if a.cmd == "tree":
            print(D.render_tree(devs))
        elif a.cmd == "show":
            print(show(D.by_id(devs, a.id)))
        elif a.cmd == "tile":
            dev = D.by_id(devs, a.id)
            print(plan_text(dev, P.plan(dev, a.dtype, a.m, a.n, a.k)))
        elif a.cmd == "compare":
            rows, skipped = compare_rows(devs, a.dtype, a.m, a.n, a.k, set(a.ids.split(",")) if a.ids else None)
            print(f"GEMM M={a.m} N={a.n} K={a.k} {a.dtype}\n")
            print(table(rows, a.md))
            if skipped:
                print("\nno native %s path: %s" % (a.dtype, ", ".join(i for i, _ in skipped)))
        elif a.cmd == "audit":
            bad = 0
            for i, problems, missing in D.audit(devs):
                for p in problems:
                    print(f"ERROR {i}: {p}"); bad += 1
                for m in missing:
                    print(f"note  {i}: {m}")
            return 1 if bad else 0
        elif a.cmd == "docs":
            print("wrote", gen_docs(devs, a.out))
    except (KeyError, P.NoFit) as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
